### ISSUE TITLE
리드미 정리 계획

### ISSUE THREAD

**Issue by hale-in** [hale-in/bbqq#2]
## To-do's
- [ ] 리팩토링 (main_train.py, main_infer.py,  main_eval.py).  pytorch-lightning, wandb
  - [ ] 코랩을 안쓰고 어떻게 리팩토링?  - 이 구조 따라가기:  https://github.com/eubinecto/the-clean-transformer/tree/main/cleanformer 
  - [ ] builders.py, fetchers.py, models.py, datamodules.py, paths.py
- [ ]  리드미 정리
  - [x] 이 프로젝트의 입력과 출력이 무엇인지 구체적인 예시를 들어서 설명
  - [x] 그럼 그런걸 왜 만들었나? 
  - [x] 어떻게 이 프로젝트에 도달 했나? (시간 순서대로 프로젝트의 역사를 노션에서 인용)
  - [ ] 어떻게 쓸 수 있는지 wandb에 사전학습된 모델을 업로드 후,  추론 할 수 있는 스크립트를 실행하는 방법
  - [ ] 학습 & 검증 & 평가 지표에 대한 설명 (그래프도 같이 있으면 좋다)
  - [ ] 우리는 어떤 사람들인가?
